### PR TITLE
Add: alert writes to elasticsearch

### PR DESCRIPTION
**Pull request by Zhang21**
增加支持将Prometheus告警记录写入到Elasticsearch7.x，可通过Kibana进行界面查看告警记录和配置表格导出。

### CODE REVIEW

**Comment by feiyu563** [comment]
非常感谢

**Comment by trestea** [comment]
使用es7.14 并没有存储告警信息，配置如下：
    #是否开启告警记录 0为关闭,1为开启
    AlertRecord=1
    alert_to_es=1
    to_es_url=http://10.170.3.11:9200
    to_es_user=elastic
    to_es_pwd=fdasrer

**Comment by Zhang21** [comment]
> 使用es7.14 并没有存储告警信息，配置如下： #是否开启告警记录 0为关闭,1为开启 AlertRecord=1 alert_to_es=1 to_es_url=http://10.170.3.11:9200 to_es_user=elastic to_es_pwd=fdasrer

有日志吗？贴下日志

**Comment by junun** [comment]
1， app.conf
AlertRecord=1
alert_to_es=1
to_es_url=http://x.x.x.x:9200/
to_es_user=elastic
to_es_pwd=xxxx

2, version info
2023/04/06 17:57:41.809 [I] [proc.go:255]  [main] 构建的Go版本: go1.17.5
2023/04/06 17:57:41.809 [I] [proc.go:255]  [main] 应用当前版本: 'v4.8.2'
2023/04/06 17:57:41.809 [I] [proc.go:255]  [main] 应用当前提交: eb8600a0597ab4f011c123083e2a457a11ea536e
2023/04/06 17:57:41.809 [I] [proc.go:255]  [main] 应用构建时间: 2022-06-24T15:42:46+0800
2023/04/06 17:57:41.809 [I] [proc.go:255]  [main] 应用构建用户: root@bogon
2023/04/06 17:57:41.828 [I] [asm_amd64.s:1581]  http server Running on http://0.0.0.0:8080

err log：
2023/04/06 16:05:57.678 [E] [prometheusalert.go:372]  [elasticsearch] Index a prometheusalert alert to es error: elastic: Error 400 (Bad Request): Rejecting mapping update to [prometheusalert-20234] as the final mapping would have more than 1 type: [_doc, prometheusalert] [type=illegal_argument_exception]

**Pull request merged**
